# Generated by Django 3.2.18 on 2023-07-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_zapunch_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapunch',
            old_name='task',
            new_name='statement',
        ),
    ]
