# Generated by Django 3.2.18 on 2023-07-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
