# Generated by Django 3.2.18 on 2023-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
