# Generated by Django 3.2.18 on 2023-07-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20230723_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emojilate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer_id', models.IntegerField()),
            ],
        ),
    ]
