# Generated by Django 3.2.18 on 2023-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_emojilate_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojilate',
            name='type',
            field=models.TextField(default='emojilate', editable=False),
        ),
        migrations.AddField(
            model_name='zapunch',
            name='type',
            field=models.TextField(default='zapunch', editable=False),
        ),
    ]
